_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 40

weights_summary: "top"
progress_bar_refresh_rate: 5

profiler: "simple"
# log_every_n_steps: 50 

# fast_dev_run: false
# limit_train_batches: 1.0
# limit_val_batches: 1.0
# limit_test_batches: 1.0
# auto_scale_batch_size: False
auto_lr_find: True
# auto_lr_num_training: 100



# tricks
# gradient_clip_val: 0
# accumulate_grad_batches: 1
# val_check_interval: 1.0
# check_val_every_n_epoch: 1
# stochastic_weight_avg: False

# debug
# num_sanity_val_steps: 2
overfit_batches: 0
# track_grad_norm: -1
# terminate_on_nan: False

# others
# amp_backend: "native"
amp_level: "02"
precision: 16
# accelerator: null
# num_nodes: 1
# tpu_cores: null
# deterministic: False

resume_from_checkpoint: null
