name: myenv

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - notebook
  - ipython
  - cudatoolkit=10.1
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip:
      - -r requirements.txt
