_target_: contrastive_learning.data.pytorch.extant.ExtantLightningDataModule

basename: "Extant"
name: '${.basename}_${.class_type}_10_${.image_size}'
batch_size: '${hparams.batch_size}'
val_split: 0.2
test_split: 0.0
num_classes: '${hparams.num_classes}'
classes: '${hparams.classes}'
image_size: '${hparams.image_size}'
channels: 3
class_type: "family"
normalize: true
predict_on_split: "val"
seed: '${seed}'
debug: '${debug}'
num_workers: 0
root_dir: ${root_dir}
dataset_dir: ${.root_dir}/datasets/${.name}