_target_: lightning_hydra_classifiers.models.resnet.ResNet


name: "resnet50"
num_classes: null
input_shape: [3, 224, 224]
optimizer:
    _target_: torch.optim.Adam
    
    name: "Adam"
    lr: 0.001
    weight_decay: 0.0
    
head: ["avg_pool","flatten","fc"]
unfreeze: ["layer4"]
root_dir: ${oc.env:WANDB_CACHE_DIR}
model_dir: ${.root_dir}/models/${.name} # null
model_path: ${.model_dir}/best_model.pkl # null