# https://wandb.ai (Weights&Biases)

wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    entity: '${oc.env:WANDB_ENTITY}' # "jrose"
    project: "image_classification"
    job_type: "train"
    group: "stage_0"
    
#     save_dir: "."
