# https://wandb.ai (Weights&Biases)

wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    entity: '${oc.env:WANDB_ENTITY}' # "jrose"
    project: "image_classification"
    job_type: "train"
    group: "${model.backbone.backbone_name}_${data.experiment.experiment_name}"
    log_model: true
#     dir: '${results_dir}/logs'
    
    
    
    
    
    
#     save_dir: "."
