model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val_loss"      # name of the logged metric which determines when model is improving
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: True         # additionaly always save model from last epoch
    mode: "min"             # can be "max" or "min"
    verbose: False
    dirpath: 'checkpoints/'
    filename: "{epoch:02d}"


early_stopping:
    _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
#     code_dir: ${work_dir}
    monitor: 'val_loss'
    patience: 3
    verbose: false
    mode: "min"
