_target_: contrastive_learning.data.pytorch.extant.ExtantLightningDataModule

basename: "Extant"
name: '${.basename}_family_10_512'
batch_size: 256
val_split: 0.0
num_classes: null
image_size: 512
channels: 3
class_type: "family"
normalize: true
seed: 98568764
predict_on_split: "val"
debug: false
num_workers: 4
root_dir: ${root_dir}
dataset_dir: ${.root_dir}/datasets/${.name}