model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/loss"
    save_top_k: 1
    save_last: true
    mode: "min"
    verbose: true
    dirpath: '${model.model_dir}/checkpoints/'
    filename: "{epoch:02d}"


early_stopping:
    _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    code_dir: ${root_dir}
    monitor: 'val_loss'
    patience: 5
    verbose: false
    mode: "min"
